# wadl2rst config file
#

src/wadl/identity-admin.wadl:
    title: Rackspace Cloud Identity Developer Guide - API v2.0
    output_directory: src/rst/identity-admin/api-operations
    
src/wadl/identity.wadl:
    title: Rackspace Cloud Identity Developer Guide - API v2.0
    output_directory: src/rst/identity/api-operations



