# wadl2rst config file
#

src/wadl/osksadm-admin.wadl:
    title: Rackspace Cloud Identity Developer Guide - API v2.0
    output_directory: src/rst/osks/api-operations

src/wadl/RAX-AUTH.wadl:
    title: Rackspace Cloud Identity Developer Guide - API v2.0
    output_directory: src/rst/raxauth/api-operations

